"""Offline deterministic fake LLM client (P2-T03).

Returns a fixed, schema-conforming JSON payload so the whole prompt -> client
-> parse -> assemble loop can be exercised with NO network and NO real model.
The returned ``test_source`` is an explicit PLACEHOLDER, not a real test, and is
never executed or written to a target project in this layer.
"""
from __future__ import annotations

import json
from typing import Optional

from app.llm.client import LLMClient, LLMResponse

# Deterministic placeholder payload conforming to LLMTestPayload.
_FAKE_PAYLOAD = {
    "imports": [
        "org.junit.jupiter.api.Test",
        "static org.junit.jupiter.api.Assertions.assertEquals",
    ],
    "test_source": (
        "// FAKE CLIENT PLACEHOLDER — not a real generated test.\n"
        "// Used only to validate prompt/context/output contracts offline.\n"
        "// Compiles & runs (so the offline pipeline reaches a PASS state) but\n"
        "// asserts nothing and covers no target code.\n"
        "import org.junit.jupiter.api.Test;\n\n"
        "class PlaceholderAiGeneratedTest {\n"
        "    @Test\n"
        "    void placeholder() {\n"
        "        // no-op\n"
        "    }\n"
        "}\n"
    ),
    "scenarios": ["placeholder: happy path", "placeholder: edge case"],
    "mocks": [],
    "notes": "Generated by FakeLLMClient for offline contract testing.",
}


class FakeLLMClient(LLMClient):
    def __init__(self, model: Optional[str] = "fake-1"):
        self.model = model

    def generate(self, prompt: str) -> LLMResponse:
        # Deterministic: ignores prompt content, returns the fixed payload.
        return LLMResponse(
            text=json.dumps(_FAKE_PAYLOAD, ensure_ascii=False),
            provider="fake",
            model=self.model,
        )
